version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
volumes:
  postgres:
