version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=mario
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=telegram_chat_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
